### ISSUE TITLE
Modify tool to create search queries using multiple keywords

### ISSUE THREAD

**Issue by DigitalCoffee** [devinc13/SENG371-Devin-and-Andrew#3]
Attempting to add more than one word as part of the search query results in only the first word being part of the query. Adding quotes causes a bad HTTP request.

An example multi-word query for looking up anti-regressive changes: "refactor OR rewrite".

**Comment by devinc13** [comment]
Fixed issue, we were missing a "+" in the query parameters. My bad! Multi word queries with spaces now work, as long as they are surrounded by quotes when typing the command line parameters. eg. q- 'refactor or rewrite'
